build: false

platform: x64

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda config --add channels conda-forge
  - "conda create -q -n test-environment python=%PYTHON_VERSION% fiona rasterio shapely click pytest"
  - activate test-environment
  - python.exe setup.py install

test_script:
  - pytest

after_test:
  - python.exe setup.py bdist_wheel

artifacts:
  - path: dist\*
